Use tf.range instead of tfnp.arange (#413)
tfnp.arange has trouble with dynamic tensors in compiled functions. The
specific error:

OperatorNotAllowedInGraphError: Using a symbolic `tf.Tensor` as a Python
`bool` is not allowed: AutoGraph did convert this function. This might
indicate you are trying to use an unsupported feature.